In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
# Importing the dataset
df = pd.read_csv('mldata.csv')
df.head()


age  weight gender likeness   height
0   27    76.0   Male  Biryani  170.688
1   41    70.0   Male  Biryani      165
2   29    80.0   Male  Biryani      171
3   27   102.0   Male  Biryani      173
4   29    67.0   Male  Biryani      164

In [5]:
# Relavent data
workshop_data = df [['age' ,'weight' , 'height']]
workshop_data.head()

age  weight   height
0   27    76.0  170.688
1   41    70.0      165
2   29    80.0      171
3   27   102.0      173
4   29    67.0      164

In [8]:

X = workshop_data.iloc[:, :-1].values #get a copy of dataset exclude last column
y = workshop_data.iloc[:, 1].values #get array of dataset in column 1st

In [9]:
X

array([[ 27.  ,  76.  ],
       [ 41.  ,  70.  ],
       [ 29.  ,  80.  ],
       [ 27.  , 102.  ],
       [ 29.  ,  67.  ],
       [ 28.  ,  46.  ],
       [ 27.  ,  64.3 ],
       [ 34.  ,  98.  ],
       [ 32.  ,  87.5 ],
       [ 22.  ,  80.  ],
       [ 29.  ,  65.  ],
       [ 29.  ,  78.  ],
       [ 23.  ,  62.  ],
       [ 28.  ,  74.  ],
       [ 25.  , 102.  ],
       [ 27.  ,  78.  ],
       [ 33.  ,  93.  ],
       [ 28.  ,  68.  ],
       [ 21.  ,  71.5 ],
       [ 25.  , 135.  ],
       [ 24.  ,  82.  ],
       [ 30.  ,  70.  ],
       [ 30.  ,  60.  ],
       [ 32.  ,  84.5 ],
       [ 30.  ,  65.  ],
       [ 25.  ,  70.  ],
       [ 34.  ,  59.  ],
       [ 32.  ,  78.  ],
       [ 24.  ,  68.  ],
       [ 30.  ,  62.  ],
       [ 21.  ,  58.  ],
       [ 31.  , 102.3 ],
       [ 22.  ,  64.  ],
       [ 19.  ,  50.  ],
       [ 30.  ,  75.  ],
       [ 27.  ,  77.  ],
       [ 34.  ,  82.72],
       [ 24.  ,  93.  ],
       [ 26.  ,  55.  ],
       [ 22.  ,  50.  ],


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [21]:
y_pred = regressor.predict(X_test)
y_pred


array([ 87.  ,  50.  ,  72.5 ,  63.  ,  88.  ,  74.  ,  54.  ,  55.  ,
        57.  ,  70.  ,  82.  ,  58.  ,  88.  ,  72.2 ,  98.  ,  63.4 ,
        75.  ,  96.  ,  55.5 ,  72.  ,  74.  ,  85.  ,  75.  ,  80.  ,
        97.  ,  84.  ,  60.  ,  87.5 ,  74.  ,  82.  ,  84.  ,  66.  ,
        46.  ,  60.  ,  62.  ,  93.  ,  50.4 ,  55.  ,  64.  ,  90.  ,
        70.  ,  50.  ,  77.  ,  53.  ,  46.  ,  53.  ,  90.  ,  71.5 ,
        65.  ,  78.  ,  67.  ,  98.  ,  75.  ,  62.  ,  68.  ,  58.  ,
        10.92,  85.  ,  77.  ,  50.  , 102.  ,  46.7 ,  70.  ,  56.  ,
        60.  ,  62.  ,  48.  ,  88.  ,  53.  ,  93.  ,  90.  ,  73.  ,
        86.  ,  67.  ,  68.  ,  63.  ,  80.  ,  50.9 ,  70.  ,  59.  ,
        56.  ,  84.  ])

In [23]:
y_pred = regressor.predict([[5,30]])
y_pred

array([30.])